# Generated by Django 3.2.7 on 2022-12-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='donate', max_length=200),
            preserve_default=False,
        ),
    ]
