# Generated by Django 3.2.7 on 2022-12-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
